# **************************************************************************** #
#                                                                              #
#                                                         ::::::::             #
#    Makefile                                           :+:    :+:             #
#                                                      +:+                     #
#    By: dvan-kle <dvan-kle@student.codam.nl>         +#+                      #
#                                                    +#+                       #
#    Created: 2024/01/12 11:02:40 by dvan-kle      #+#    #+#                  #
#    Updated: 2024/01/12 11:03:45 by dvan-kle      ########   odam.nl          #
#                                                                              #
# **************************************************************************** #

CC = g++
CFLAGS = -Wall -Werror -Wextra -std=c++98

megaphone: megaphone.cpp
	$(CC) $(CFLAGS) -o megaphone megaphone.cpp

clean:
	rm -f megaphone